# Sensitivity analysis
How many cells do we need for a method to detect immune cell infiltration?

```{r}
show_cell_types = c("B cell", "Dendritic cell", "Macrophage/Monocyte", "NK cell", "T cell CD4+", "T cell CD8+")

n_immune_cells = rep(c(seq(0, 50, 5)
                     , seq(60, 100, 10)
                     , seq(150, 500, 50)
                     , seq(600, 1000, 100)
                     ), 5)
```

```{r, fig.height=18, fig.width=25, cache=TRUE}
sensitivity_analysis_file = "../results/cache/sensitivity_analysis_res.rda"
if(!file.exists(sensitivity_analysis_file)) {
  set.seed(42)
  registerDoMC(cores=16)
  res = foreach(input_cell_type = show_cell_types,
                .final = function(x) setNames(x, show_cell_types)) %:% 
    foreach(method = immunedeconv::deconvolution_methods,
            .final = function(x) setNames(x, immunedeconv::deconvolution_methods)) %dopar% {
      expr_mat = lapply(n_immune_cells, function(k) {
        cell_n = make_cell_fraction_vector(input_cell_type, k)
        cell_frac = cell_n/sum(cell_n)
        make_random_bulk(eset=single_cell_schelker$eset, cell_fractions = cell_frac, n_cells = sum(cell_n))
      }) %>% bind_cols() %>% as.matrix()
      
      
      rownames(expr_mat) = rownames(single_cell_schelker$eset %>% exprs())
      
      deconvolute(expr_mat, method)
    }
  
  sensitivity_analysis_res = res
  save(sensitivity_analysis_res, file=sensitivity_analysis_file)
}


```

## post-process the deconvolution results
```{r, cache=TRUE}
load(sensitivity_analysis_file)

all_results = foreach(input_cell_type = show_cell_types, 
        .combine=bind_rows) %:% 
  foreach(method = immunedeconv::deconvolution_methods,
          .combine=bind_rows) %do% {
    tmp_res = sensitivity_analysis_res[[input_cell_type]][[method]] %>%
                map_result_to_celltypes(show_cell_types, method) %>%
                na.omit() 
    
    n_cell_df = tibble(sample=colnames(tmp_res),
                       n_immune_cells = n_immune_cells,
                       n_background_cells = sum(cell_types$n_background_cells)) 
                  
    
    tmp_res %>%
      as_tibble(rownames = "cell_type") %>%
      gather(sample, estimate, -cell_type) %>%
      mutate(method=method, input_cell_type=input_cell_type) %>%
      inner_join(n_cell_df, by="sample")
} %>% 
  select(-sample) %>% 
  mutate(frac_immune_cells = as.factor(round(n_immune_cells/cell_types$n_background_cells * 100, 2)))

all_results2 = all_results %>% 
  group_by_at(vars(-estimate)) %>% 
  summarise_all(funs(mean, sd, n=length)) %>%
  mutate(ci=qt(0.975,df=n-1)*sd/sqrt(n)) %>%
  ungroup()
```

```{r, fig.height=18, fig.width=25, cache=TRUE}
all_results2 %>% 
  ggplot(aes(x=frac_immune_cells, y=mean, colour=cell_type)) +
  #   geom_line() + 
    geom_errorbar(aes(ymin=mean-ci, ymax=mean+ci)) + 
    theme(axis.text.x=element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position="top") + 
    facet_grid(method~input_cell_type, scales = "free_y") + 
    scale_color_manual(values = color_scales$immune_cells)
```

### Summary figure: At which percentage the method captures the cell type above noise level? 
```{r, warning=FALSE, message=FALSE, cache=TRUE}
# add fallback values, if none of the fractions exceed the specified value
results_inf_fallback = all_results2 %>%
  select(cell_type, method, input_cell_type) %>%
  distinct() %>% 
  mutate(mean = if_else(cell_type == input_cell_type, Inf, 0), ci=0, frac_immune_cells = as.factor(Inf))

# omit unnecessary columns and append fallback Inf valuees
all_results3 = all_results2 %>% 
  select(cell_type, method, input_cell_type, mean, ci, frac_immune_cells) %>% 
  bind_rows(results_inf_fallback)

# add the 'reference cell type', i.e. the celltype that *should* be there as an additional column
ref_cell_type = all_results3 %>% 
  filter(cell_type == input_cell_type) %>% 
  select(input_cell_type, method, frac_immune_cells, ref_mean=mean, ref_ci=ci)

all_combinations = crossing(method=immunedeconv::deconvolution_methods, input_cell_type=show_cell_types)

# filter and summarise, s.t. we end up having the minimal fraction at which the celltype is distinguishable from the others
sensitivity_plot = all_results3 %>% 
  filter(cell_type != input_cell_type) %>% 
  select(cell_type, method, input_cell_type, mean, ci, frac_immune_cells) %>% 
  inner_join(ref_cell_type) %>% 
  # at least 0.001 predicted to avoid numerical problems with very small values (-> xCell). 
  mutate(significantly_enriched = ref_mean-ci > mean+ci & ref_mean > 1e-3) %>%
  filter(significantly_enriched) %>%
  group_by(method, input_cell_type, cell_type) %>% 
  summarise(min_frac = min(as.numeric(as.character(frac_immune_cells)))) %>% 
  group_by(method, input_cell_type) %>% 
  # must exceed *all* other cell types
  summarise(min_frac = max(as.numeric(as.character(min_frac)))) %>% 
  right_join(all_combinations)
  

```

```{r, fig.width=7, fig.height=6, cache=TRUE}
sensitivity_plot %>%
  mutate(min_frac=ifelse(is.infinite(min_frac), 100, min_frac)) %>% 
  mutate(not_measured=ifelse(is.na(min_frac), "yes", "no")) %>%
  mutate(min_frac=ifelse(is.na(min_frac), 100, min_frac)) %>% 
  ggplot(aes(x=method, y=min_frac, fill=method, alpha=not_measured)) + 
  geom_bar(stat='identity') + 
  facet_wrap(~input_cell_type, nrow=2, labeller = label_wrap_gen()) +  
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position="top",
        strip.text.x = element_text(size=9)) +
  scale_fill_manual(values=color_scales$methods) + 
  scale_alpha_manual(values=c("yes"=.3, "no"=1.)) + 
  ggtitle("Sensitivity")

```


### Summary figure: predicted amount of cells when there are none
```{r, fig.height=6, fig.width=6}
all_results %>% 
  filter(frac_immune_cells == 0, cell_type == input_cell_type) %>%
  filter(method != "mcp_counter") %>% 
  ggplot(aes(x=method, y=estimate, color=method)) + 
    geom_boxplot(position="dodge") + 
    facet_wrap(~cell_type) + 
    theme(axis.text.x=element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position="top",
          strip.text.x = element_text(size=9)) +
    scale_color_manual(values=color_scales$methods) 

```
