---
title: "R Notebook"
output: html_notebook
---

```{r}
racle_bulk_mat = racle_expression %>% as.data.frame() %>% column_to_rownames("hgnc_symbol") %>% as.matrix()
hoeck_bulk_mat = hoeck_mixture
# ovarian_bulk_mat
```


## Run the deconvolution
We first run all methods that are integrated in the `immune_deconvolution_methods` are package automatically in a loop. 
```{r, cache=TRUE}
all_results_racle = lapply(immunedeconv::deconvolution_methods, function(method) {
  deconvolute(racle_bulk_mat, method) %>%
    mutate(method=method) %>%
    map_results_to_dataset("racle") %>% 
    group_by(method, racle) %>%   
    summarise_all(funs(sum)) 
})
all_results_hoeck = lapply(immunedeconv::deconvolution_methods, function(method) {
  deconvolute(hoeck_bulk_mat, method) %>%
    mutate(method=method) %>%
    map_results_to_dataset("hoeck") %>% 
    group_by(method, hoeck) %>%   
    summarise_all(funs(sum)) 
})
all_results_schelker = lapply(immunedeconv::deconvolution_methods, function(method) {
  deconvolute(ovarian_bulk_mat, method) %>%
    mutate(method=method) %>%
    map_results_to_dataset("single_cell_schelker") %>% 
    group_by(method, single_cell_schelker) %>%   
    summarise_all(funs(sum)) 
})
```


```{r, cache=TRUE, eval=FALSE}
# immunedeconv::export_for_timer(ovarian_bulk_mat, path="../results/timer_input_ovarian_bulk.tsv")
# 
# res_timer = immunedeconv::import_from_timer("../data/timer/timer_result_ovarian_bulk.csv") %>%
#   mutate(method="timer")
```

```{r, cache=TRUE}
hoeck_ref2 = hoeck_ref %>% as_tibble(rownames="sample") %>% gather(cell_type, true_fraction, -sample)
hoeck2 = bind_rows(all_results_hoeck) %>% gather(sample, estimate, -method, -hoeck) %>% mutate(dataset="hoeck") %>% rename(cell_type=hoeck) %>% inner_join(hoeck_ref2)

racle_ref2 = racle_cyto %>% rename(sample=`donor ID`) %>% gather(cell_type, true_fraction, -sample) %>% mutate(true_fraction=true_fraction/100)
racle2 = bind_rows(all_results_racle) %>% gather(sample, estimate, -method, -racle) %>% mutate(dataset="racle") %>% rename(cell_type=racle) %>% inner_join(racle_ref2)

schelker_ref2 = schelker_ref
schelker2 = bind_rows(all_results_schelker) %>% gather(sample, estimate, -method, -single_cell_schelker) %>% mutate(dataset="single_cell_schelker") %>% rename(cell_type=single_cell_schelker) %>% inner_join(schelker_ref2)


all_results_tidy_val = bind_rows(hoeck2, racle2, schelker2) %>% ungroup()

```


```{r, fig.width=10, fig.height=6}
all_results_tidy_val %>% filter(cell_type %in% c("B cells", "Bcells")) %>%
  ggplot(aes(x=true_fraction, y=estimate)) + geom_point(aes(color=method, shape=dataset)) + 
  scale_color_manual(values=color_scales$methods) + 
  facet_wrap(~method, scales = "free") + 
  stat_cor() + 
  ggtitle("B cells")

```


```{r, fig.width=10, fig.height=6}
all_results_tidy_val %>% filter(cell_type %in% c("Dendritic cells", "DC")) %>%
  ggplot(aes(x=true_fraction, y=estimate)) + geom_point(aes(color=method, shape=dataset)) + 
  scale_color_manual(values=color_scales$methods) + 
  facet_wrap(~method, scales = "free") + 
  stat_cor() + 
  ggtitle("Dendritic cells")

```


```{r, fig.width=10, fig.height=6}
all_results_tidy_val %>% filter(cell_type %in% c("CD8+ T cells", "CD8 T cells")) %>%
  ggplot(aes(x=true_fraction, y=estimate)) + geom_point(aes(color=method, shape=dataset)) + 
  scale_color_manual(values=color_scales$methods) + 
  facet_wrap(~method, scales = "free") + 
  stat_cor() + 
  ggtitle("CD8 T")

```

```{r, fig.width=10, fig.height=6}
all_results_tidy_val %>% filter(cell_type %in% c("CD4+ T cells", "CD4 T cells")) %>%
  ggplot(aes(x=true_fraction, y=estimate)) + geom_point(aes(color=method, shape=dataset)) + 
  scale_color_manual(values=color_scales$methods) + 
  facet_wrap(~method, scales = "free") + 
  stat_cor() + 
  ggtitle("CD4 T")

```

```{r, fig.width=10, fig.height=6}
all_results_tidy_val %>% filter(cell_type %in% c("Natural killer cells", "NK", "NK cells")) %>%
  ggplot(aes(x=true_fraction, y=estimate)) + geom_point(aes(color=method, shape=dataset)) + 
  scale_color_manual(values=color_scales$methods) + 
  facet_wrap(~method, scales = "free") + 
  stat_cor() + 
  ggtitle("NK")

```