# Creating publication ready figures
```{r cache_fig_results, include=FALSE}
### Cache and load data
save(res_mixing_study, res_validation,
     res_sensitivity, res_spillover, res_methods_validity,
     file="../results/cache/results_for_figures.rda")
load("../results/cache/results_for_figures.rda")
theme_set(theme_cowplot(font_size=11)) # reduce default font siz

#### Figure dimensions
# (BioMed Central standard dimensions)
# full width page: 170mm
# full page height: 225mm (for figure and legend)
WIDTH = 183
HEIGHT = 247
```

```{r define_names, include=FALSE}
# Define names
tmp_names = names(config$deconvolution_methods)
tmp_names[tmp_names == "CIBERSORT (abs.)"] = "CIBERSORT abs"
method_names = tibble(
  method = config$deconvolution_methods,
  method_name = factor(tmp_names, levels=sort(tmp_names, decreasing = FALSE))
) %>% arrange(method_name)


method_abbrev = c("mcp_counter"="MCP", "epic"="EPC", "quantiseq"="QTS", "xcell"="XCL",
                  "cibersort"="CBS", "cibersort_abs"="CBA", "timer"="TMR")

# fallback if method abbrev is not defined
method_names %<>% left_join(tibble(method=names(method_abbrev), method_abbrev=method_abbrev)) %>%
  mutate(method_abbrev = if_else(is.na(method_abbrev), toupper(substr(method, 0, 3)), method_abbrev))

cell_type_names = tibble(
  cell_type      = c("B cell", "Dendritic cell", "Macrophage/Monocyte",
                     "NK cell", "T cell CD4+", "T cell CD8+", "T cell CD4+ (non-regulatory)",  "T cell regulatory (Tregs)",
                     "Monocyte", "T cell", "Cancer associated fibroblast", "Endothelial cell"),
  cell_type_name = c("B",      "DC",             "Mac/Mono",
                     "NK",      "T CD4+",      "T CD8+" ,     "T CD4+ n.r.",                   "T reg",
                     "Mono",     "T",      "CAF",                          "Endo")
)

validation_datasets = tibble(
  dataset = c("all", "hoek", "racle", "schelker_ovarian"),
  dataset_name = c("All datasets\n(n=15)", "Hoek\n(PBMC, n=8)", "Racle\n(melan., n=4)", "Schelker\n(ovarian, n=3)")
)

HEATMAP_FONT_SIZE = 2.7
```


```{r, define_cor_table, include=FALSE}
#' plot correlations as a table colored by the absolute value.
plot_cor_table = function(data, dataset="none") {
  if(!("asterisk" %in% names(data))) {
    data %<>% mutate(asterisk = "no")
  }
  if(!("category" %in% names(data))) {
    data %<>% mutate(category = dataset)
  }
  data %>%
    mutate(pearson_text = if_else(pearson < 0, "< 0", as.character(round(pearson, 2))),
           pearson = if_else(pearson < 0, 0, pearson)) %>%
    mutate(asterisk = if_else(is.na(asterisk), "no", asterisk)) %>%
    mutate(pearson_text = if_else(asterisk == "yes", paste0(pearson_text, "*"), pearson_text)) %>%
    mutate(pearson_text = if_else(is.na(pearson), "n/a", pearson_text),
           pearson = if_else(is.na(pearson), 0, pearson)) %>%
    inner_join(method_names) %>%
    ggplot(aes(x=column, y=reorder(method_abbrev, -order(method_abbrev)))) +
      geom_tile(aes(fill=pearson)) +
      geom_text(aes(label=pearson_text), size=HEATMAP_FONT_SIZE) +
      scale_fill_distiller(type="div", palette = "RdYlGn", direction=1, values=c(0,1), limits=c(0, 1)) +
      theme_benchmark() +
      theme(axis.text.x.top=element_text(angle = 90, vjust = .5, hjust=0),
              legend.position="none",
              strip.text.x = element_text(size=11)) +
      facet_wrap(~category, scales = "free", strip.position="left", nrow=1) +
      # theme(strip.background = element_blank(),
      #       strip.text.x = element_blank()) +
      scale_x_discrete(position = "top") +
      xlab(NULL) +
      ylab(NULL) +
      theme_title(hjust=0.5)
}

```






## Predictions on simulated vs. genuine bulk
```{r, method-validity-f1a, fig.width=7, fig.height=2, message=FALSE, warning=FALSE, echo=FALSE, fig.cap="Predictions on simulated vs. genuine bulk"}
fun_breaks3 = function(limits) {
  breaks = signif(max(limits) * c(0.25, 0.75),1)
  names(breaks) = attr(breaks, "labels")
  breaks
}

tmp_cor = res_methods_validity$all_results_mapped %>%
  group_by(method) %>%
  do(make_cor(.$bulk, .$simulated)) %>%
  mutate(pearson=round(pearson, 2)) %>%
  inner_join(method_names)

res_methods_validity$all_results_mapped %>%
  inner_join(cell_type_names) %>%
  inner_join(method_names) %>%
  ggplot(aes(x=bulk, y=simulated)) +
  geom_point(aes(colour=cell_type_name), size=.5) +
  facet_wrap(~method_name, scales="free", nrow=1) +
  theme(legend.position = "top") +
  geom_text(data=tmp_cor, mapping=aes(label=paste0("r=", pearson), x=0, y=0), hjust=0, vjust=-8, size=2.4) +
  panel_border() +
  scale_x_continuous(breaks=fun_breaks3) +
  scale_y_continuous(breaks=fun_breaks3) +
  theme(strip.text=element_text(size=6),
        panel.spacing = unit(2, "mm"), axis.text = element_text(size=8))
```


```{r, mixing-corr, fig.width=7, fig.height=6, message=FALSE, warning=FALSE, echo=FALSE}
fun_breaks = function(limits) {
  breaks = signif(max(limits) * c(0.25, 0.75),1)
  names(breaks) = attr(breaks, "labels")
  breaks
}

corr_annot = res_mixing_study$correlations %>%
  select(method, cell_type, pearson, p_signif) %>%
  mutate(pearson = round(pearson, 2)) %>%
  inner_join(method_names) %>%
  inner_join(cell_type_names) %>%
  mutate(cell_type_name_f = factor(cell_type_name, levels=cell_type_names$cell_type_name)) %>%
  distinct()

plot_mixing = res_mixing_study$all_results %>%
  inner_join(method_names) %>%
  inner_join(cell_type_names) %>%
  mutate(cell_type_name_f = factor(cell_type_name, levels=cell_type_names$cell_type_name)) %>%
  ggplot(aes(x=true_fraction, y=estimate)) +
    geom_point(size=.2) +
    geom_text(data=corr_annot, mapping=aes(label=paste0("r=", pearson, ", ", p_signif), x=-Inf, y=-Inf), hjust=-0.1, vjust=-6.8, size=2.4) +
    facet_grid(method_abbrev ~ cell_type_name_f, scales="free") +
    stat_smooth(color="blue", method="lm", size=.4) +
    scale_color_manual(values=color_scales$methods, na.value="grey") +
    scale_x_continuous(breaks=c(.2)) +
    scale_y_continuous(breaks=fun_breaks) +
    theme(legend.position = "none", strip.text=element_text(size=8),
          panel.spacing = unit(.5, "mm"), axis.text = element_text(size=8)) +
    ylab("estimated fraction") +
    xlab("true fraction") +
    panel_border()

# ggsave("../results/figures/correlations_mixing.pdf", width=WIDTH, height=140, units = "mm")
# ggsave("../results/figures/correlations_mixing.png", width=WIDTH, height=140, units = "mm", dpi=600)
```

```{r validation_benchmark, include=FALSE}
# Validation Benchmark
ALL_CELLS = "All cells"
use_cell_types = c("B cell", "Dendritic cell", "Monocyte", "NK cell", "T cell CD4+", "T cell CD8+", "T cell")

validation = new.env()
validation$all_results = res_validation$all_results %>% filter(cell_type %in% use_cell_types) %>%
  filter(!(cell_type == "T cell" & dataset != "hoek")) %>% # otherwise t cells are counted twice!
  inner_join(cell_type_names)

validation$all_datasets = validation$all_results %>%
  group_by(method, cell_type_name, cell_type) %>%
  do(make_cor(.$estimate, .$true_fraction)) %>%
  mutate(asterisk = if_else(cell_type == "Monocyte" & method == "mcp_counter", "yes", "no")) %>%
  mutate(category = validation_datasets[validation_datasets$dataset == 'all', "dataset_name"] %>% pull(), column=cell_type_name)

validation$hoek = validation$all_results %>%
  filter(dataset == 'hoek') %>%
  group_by(method, cell_type_name, cell_type) %>%
  do(make_cor(.$estimate, .$true_fraction)) %>%
  mutate(asterisk = if_else(cell_type == "Monocyte" & method == "mcp_counter", "yes", "no")) %>%
  mutate(category = validation_datasets[validation_datasets$dataset == 'hoek', "dataset_name"] %>% pull()) %>%
  mutate(column = cell_type_name)
```


```{r validation-benchmark-all-cells, fig.width=4, fig.height=7, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Comparison of absolute predictions for three validation dataset. "}
val_results_all = res_validation$all_results %>%
  mutate(dataset2 = dataset) %>%
  bind_rows(res_validation$all_results %>% mutate(dataset2 = "all")) %>%
  filter(!(cell_type == "T cell" & dataset != "hoek")) %>%
  inner_join(method_names) %>%
  inner_join(validation_datasets, by=c("dataset2"="dataset"))

corr_annot = val_results_all %>%
  group_by(dataset2, method) %>%
  do(make_cor(.$true_fraction, .$estimate)) %>%
  select(method, dataset2, pearson, p_signif) %>%
  mutate(pearson = round(pearson, 2)) %>%
  inner_join(method_names) %>%
  inner_join(validation_datasets, by=c("dataset2"="dataset")) %>%
  distinct()

p_validation_all_cells = val_results_all %>%
  ggplot(aes(x=true_fraction, y=estimate)) +
    geom_point(aes(color=cell_type), size=.4) +
    geom_text(data=corr_annot, mapping=aes(label=paste0("r=", pearson, ", ", p_signif), x=-Inf, y=-Inf), hjust=-0.1, vjust=-6.8, size=2.4) +
    scale_color_manual(values=color_scales$validation) +
    facet_grid(method_abbrev~dataset_name, scales = "free_y") +
    scale_x_continuous(breaks=c(.5)) +
    scale_y_continuous(breaks=fun_breaks) +
    theme(legend.position = "top", strip.text=element_text(size=8),
          panel.spacing = unit(.5, "mm"), axis.text = element_text(size=8)) +
    guides(colour = guide_legend(override.aes = list(size=2), nrow=4, title="cell type")) +
    ylab("estimated fraction") +
    xlab("true fraction") +
    panel_border()
```


```{r, fig.height=3.5, include=FALSE}
p_validation_all_datasets = validation$all_datasets %>%
  plot_cor_table()

p_validation_hoek = validation$hoek %>%
  plot_cor_table()

print(p_validation_all_datasets)
print(p_validation_hoek)
```



## Benchmark results
```{r, fig.height=8.5, fig.width=7, echo=FALSE, message=FALSE, warning=FALSE, fig.cap="Benchmark results main figure. "}
# combine heatmaps

## margins
MT1 = 0
MB1 = .5
MR1 = .3
ML1 = .5

p2_validation_all_cells = p_validation_all_cells + theme(legend.position = "none")
p2_validation_all_cells_legend = get_legend(p_validation_all_cells)

plots_left = align_plots(plot_mixing, p2_validation_all_cells, align="v", axis="l")


## fine-tune formatting
p2_validation_all_datasets = p_validation_all_datasets  +
  theme(plot.margin = margin(t=MT1, b=MB1, r=MR1, unit="cm", l=ML1))
p2_validation_hoek = p_validation_hoek + theme(plot.margin = margin(t=MT1, b=MB1, r=MR1, l=ML1, unit="cm"))

plot_validation = plot_grid(p2_validation_all_datasets, p2_validation_hoek,
          align = "v",
          nrow = 2,
          axis="lr",
          hjust = -.5,
          label_size = 12,
          labels=c("c", "d"),
          rel_heights = c(.5, .5))

plot_val_legend = plot_grid(plot_validation, p2_validation_all_cells_legend,
                            nrow=2,
                            rel_heights =c(.8, .2))

p_lower = plot_grid(plots_left[[2]], plot_val_legend,
                    nrow=1,
                    labels=c("b"),
                    label_size=12,
                    rel_widths = c(.5, .5))

plot_grid(plots_left[[1]], p_lower, align="h", ncol=1, axis="lr", labels = "a", rel_heights = c(.5, .5), label_size = 12)

ggsave("../results/figures/summary.pdf", height = HEIGHT, width = WIDTH, units = "mm")
ggsave("../results/figures/summary.png", height = HEIGHT, width = WIDTH, units = "mm", dpi=400)
```



## detection limit / false positive figure
```{r detection-limit-fp, fig.width=6.9, fig.height=6.5, message=FALSE, warning=FALSE, echo=FALSE, fig.cap="Detection limit and false positives."}
data = res_sensitivity$background_data %>%
  inner_join(method_names) %>%
  inner_join(cell_type_names)

data_detection_limit = res_sensitivity$data_detection_limit %>%
  inner_join(method_names) %>%
  inner_join(cell_type_names) %>%
  ungroup()

data_false_positives = res_sensitivity$data_false_positives %>%
  inner_join(method_names) %>%
  inner_join(cell_type_names) %>%
  ungroup()

fun_breaks2 = function(limits) {
  breaks = signif(max(limits) * c(0, 0.5),1)
  names(breaks) = attr(breaks, "labels")
  breaks
}

data %>%
  ggplot(aes(x=frac_immune_cells, y=mean)) +
    geom_ribbon(aes(ymin=mean-ci, ymax=mean+ci), alpha=.2) +
    geom_point(size=.2, shape=4) +
    # geom_errorbar(aes(ymin=mean-ci, ymax=mean+ci)) +
    panel_border() +
    facet_grid(method_abbrev ~ cell_type_name, scales = "free_y") +
    scale_x_continuous(breaks=c(.0, .2), limits=c(0, 0.25)) +
    scale_y_continuous(breaks=fun_breaks2) +
    geom_hline(mapping=aes(yintercept=0, colour="zero"), linetype="dashed", show.legend=FALSE) +
    geom_vline(mapping=aes(xintercept = 0, color="zero"), linetype="dashed", show.legend=FALSE) +
    # geom_abline(mapping=aes(slope=1, intercept=0), color="grey", linetype="solid", show.legend = FALSE) +
    geom_vline(data=data_detection_limit, mapping=aes(xintercept=min_frac, colour="minimal detection fraction"), show.legend = FALSE) +
    geom_hline(data=data_false_positives, mapping=aes(yintercept=fp_prediction, colour="background prediction fraction")) +
    geom_hline(yintercept = 0, mapping = aes(colour="detection limit"), alpha=0) + # fake line to fix legend
    ylab("average estimate") +
    xlab("fraction of spike-in cells") +
    theme(legend.position = "top", strip.text=element_text(size=8),
          panel.spacing = unit(1, "mm"), axis.text = element_text(size=8)) +
    scale_color_manual(values=c("zero"="grey", "minimal detection fraction"="red", "background prediction fraction"="blue"), guide=guide_legend("performance measure", override.aes = list(alpha=1)))

ggsave("../results/figures/detection_limit_fp.pdf", width = WIDTH, height=170, units = "mm")
ggsave("../results/figures/detection_limit_fp.png", width = WIDTH, height=170, units = "mm", dpi=600)
```

```{r summary-table-tsv, include=FALSE}
summary_table = res_mixing_study$correlations %>%
  inner_join(cell_type_names) %>%
  inner_join(method_names) %>%
  select(cell_type_name, method_name, pearson) %>%
  full_join(select(data_detection_limit, method_name, cell_type_name, min_frac)) %>%
  full_join(select(data_false_positives, method_name, cell_type_name, fp_prediction)) %>%
  mutate(min_frac=round(min_frac, 3), fp_prediction=round(fp_prediction, 3)) %>%
  mutate(pearson=if_else(pearson < 0, "< 0", as.character(round(pearson, 2)))) %>%
  select(`cell type`=cell_type_name, `method`=method_name, correlation=pearson,
         `detection limit`=min_frac, `false positives`=fp_prediction) %>%
  arrange(`cell type`, `method`)

summary_table %>%
  write_tsv("../results/tables/summary_table.tsv")

```

## Migration charts for Spillover analysis
```{r, fig.width = 16, fig.height=10, include=FALSE}
methods = config$deconvolution_methods

# cibersort and cibersort abs are identical in this analysis, no need to include both.
methods = sort(methods[methods != "cibersort_abs"])
tmp_method_names = as.list(method_names %>% pull(method_name))
names(tmp_method_names) = method_names$method

migration = res_spillover$all_results %>%
  filter(dataset == "artificial_bulk") %>%
  group_by(method, cell_type, true_cell_type) %>%
  summarise(estimate = mean(estimate)) %>%
  ungroup()

noise_ratio = migration %>%
  group_by(method) %>%
  mutate(type = ifelse(cell_type == true_cell_type, "signal", "noise")) %>%
  group_by(method, type) %>%
  summarise(estimate = sum(estimate)) %>%
  spread(type, estimate) %>%
  mutate(noise_ratio = noise/(signal+noise)) %>%
  ungroup()

layout(matrix(seq(1, 6), 2, 3))
par(mar=rep(0.5, 4))
circos.par(cell.padding = rep(0, 4))
x = lapply(methods, function(method) {
      tmp_migration = migration %>%
        filter(method == !!method) %>%
        select(-method) %>%
        spread(cell_type, estimate) %>%
        as.data.frame() %>%
        column_to_rownames("true_cell_type") %>%
        as.matrix()

      chordDiagram(tmp_migration, directional = TRUE, transparency = .5,
                   grid.col = color_scales$immune_cells,
                   annotationTrack = c("grid"),
                   annotationTrackHeight = uh(5, "mm")
                   )

      text(0, 0, tmp_method_names[[method]], cex = 2.3)
      text(0, -0.25, as.character(round(filter(noise_ratio, method == !!method) %>% pull(noise_ratio), 2)), cex=2.2)
})

grid.echo()
migration_plot = grid.grab()
```

```{r, include=FALSE}
# make legend using ggplot
tmp_barplot_data = migration %>%
  select("cell type" = cell_type) %>%
  # add arbitrary value
  mutate(value = 1)

p = tmp_barplot_data %>%
  ggplot(aes(x=`cell type`, y=value, fill=`cell type`)) +
  geom_bar(stat='identity') +
  scale_fill_manual(values=color_scales$immune_cells) +
  theme(legend.position = "top", legend.justification = "center")
p

migration_legend = cowplot::get_legend(p)
```

```{r, include=FALSE}
# Plot differences with removed marker genes
rmgenes_plot_dc = res_spillover$rm_marker_genes_dc %>%
  inner_join(method_names) %>%
  filter(cell_type == "B cell") %>%
  mutate(dataset = if_else(dataset == "before", "no", "yes")) %>%
  ggplot(aes(x=dataset, y=predicted_fraction, colour=dataset)) +
    geom_quasirandom() +
    stat_summary(fun.y=mean, geom="crossbar", fun.ymin=mean, fun.ymax=mean, width=.5, color="black") +
    facet_wrap(~method_name, drop = TRUE) +
    stat_compare_means(paired = TRUE, method = "t.test", label="p.signif") +
    theme(legend.position = "none") +
    xlab("signature genes removed") +
    ylab("predicted B cell score") +
    scale_color_brewer(type="qual", palette=6, direction = -1) +
    ylim(0, .75) +
    theme(plot.margin = margin(t=1, unit = "cm"))

```

```{r, include=FALSE}
rmgenes_plot_cd4 = res_spillover$rm_marker_genes_cd4 %>%
  inner_join(method_names) %>%
  filter(cell_type == "T cell CD4+") %>%
  mutate(dataset = if_else(dataset == "before", "no", "yes")) %>%
  ggplot(aes(x=dataset, y=predicted_fraction, colour=dataset)) +
    geom_quasirandom() +
    stat_summary(fun.y=mean, geom="crossbar", fun.ymin=mean, fun.ymax=mean, width=.5, color="black") +
    facet_wrap(~method_name, drop = TRUE) +
    stat_compare_means(paired = TRUE, method = "t.test", label="p.signif") +
    theme(legend.position = "none") +
    xlab("signature genes removed") +
    ylab("predicted CD4⁺ T cell score") +
    scale_color_brewer(type="qual", palette=6, direction = -1) +
    ylim(0, .5) +
    theme(plot.margin = margin(t=1, unit = "cm"))


```

```{r fig.width = 8, fig.height=9, echo=FALSE, message=FALSE, fig.cap="Migration chart figure for paper. "}
# combine legend and plot
plot_lower = plot_grid(rmgenes_plot_cd4, rmgenes_plot_dc,
                       nrow=1, rel_widths = c(0.5, 0.5), align = "h", labels = c("b", "c"))

plot_grid(migration_plot, migration_legend, plot_lower,
          nrow=3, rel_heights = c(0.7, .15, .4), align = "v", labels = c("a", "", ""), axis="t")

ggsave("../results/figures/spillover_migration_chart.pdf", width=WIDTH, height=205, units = "mm")
ggsave("../results/figures/spillover_migration_chart.png", width=WIDTH, height=205, units = "mm", dpi=600)
```
