```{r}
tref = EPIC::TRef$refProfiles[EPIC::TRef$sigGenes,]

tref = as_tibble(tref, rownames="gene") %>% 
  arrange(-(CD4_Tcells * Endothelial))

til10 = read_tsv("../immunedeconv/inst/extdata/quantiseq/TIL10_signature.txt") %>% 
  arrange()

samples = sensitivity_analysis_dataset$`T cell CD4+`[,n_immune_cells == 0]

samples_median = apply(samples, 1, median)
```

```{r}
tref$background = samples_median[tref$gene]
til10$background = samples_median[til10$ID]

View(arrange(tref, CD4_Tcells * -background))
View(arrange(til10, T.cells.CD4 * -background))

```

# EPIC
## CAFS
TSPYL1

## ENDO
DGKA
CD79B

## background
TSPYL1
GNLY
DGKA

#quanTIseq

## background
FHIT
GNG2



```{r}
exclude_genes = c("FHIT", "GNG2", "TSPYL1", "DGKA", "CD79B")

samples = sensitivity_analysis_dataset$`T cell CD4+`[,n_immune_cells == 0]

use_methods = intersect(c("epic", "quantiseq"), config$deconvolution_methods)

show_cell_types = c("B cell", "Dendritic cell", "Macrophage/Monocyte",
                    "NK cell", "T cell CD4+", "T cell CD8+")
timer_indications = rep("OV", ncol(samples))

res_before = foreach(method=use_methods,
                     .combine=bind_rows) %do% {
                       deconvolute(samples, method=method, indications=timer_indications) %>%
                         map_result_to_celltypes(show_cell_types, method) %>%
                         as_tibble(rownames = "cell_type") %>%
                         mutate(method=method, dataset="before")
                     }

res_after = foreach(method=use_methods,
                     .combine=bind_rows) %do% {
                       deconvolute(samples, method=method, indications=timer_indications, rmgenes=exclude_genes) %>%
                         map_result_to_celltypes(show_cell_types, method) %>%
                         as_tibble(rownames = "cell_type") %>%
                         mutate(method=method, dataset="after")
                     }

res_all = bind_rows(res_before, res_after) %>%
  gather(sample, predicted_fraction, -cell_type, -method, -dataset) %>%
  mutate(dataset = factor(dataset, levels=c("before", "after")))

res_spillover$rm_marker_genes = res_all

```

```{r, fig.width=12, echo=FALSE, message=FALSE, fig.cap="Predictions on 10 simulated DC samples before and after removal of the six genes. ", warning=FALSE}
res_all %>%
  ggplot(aes(x=dataset, y=predicted_fraction, colour=dataset)) +
    geom_quasirandom() +
    stat_summary(fun.y=mean, geom="crossbar", fun.ymin=mean, fun.ymax=mean, width=.5, color="black") +
   facet_grid(method~cell_type, drop = TRUE, scales = "free") +
  stat_compare_means(paired = TRUE, method = "t.test")


```
