```{r child = '05_input_data.Rmd'}
```

```{r, cache=TRUE}
bulk_mean = sapply(colnames(schelker_ovarian$expr_mat), function(donor) {
  ind = pData(single_cell_schelker$eset)$donor == donor
  apply(exprs(single_cell_schelker$eset)[,ind], 1, mean)
})
bulk_mean = apply(bulk_mean, 2, scale_to_million)
```

```{r}
use_cell_types = c("T cell", "T cell CD8+", "T cell CD4+",
                   "Macrophage/Monocyte", "B cell",
                   "Dendritic cell", "NK cell", "Neutrophil")
```

We run all methods on both datasets and compare the results.
```{r, cache=TRUE, message=FALSE, echo=FALSE, warning=FALSE, results='hide'}
timer_indications = rep("OV", ncol(schelker_ovarian$expr_mat))
all_results_bulk = foreach(method = config$deconvolution_methods,
                           .combine=bind_rows) %do% {
                             deconvolute(schelker_ovarian$expr_mat, method, indications=timer_indications) %>%
                               map_result_to_celltypes(use_cell_types, method=method) %>%
                               as_tibble(rownames="cell_type") %>%
                               mutate(method=method) %>%
                               mutate(source="bulk") 
                           }

all_results_simulated = foreach(method=config$deconvolution_methods,
                                .combine=bind_rows) %do% {
                                  deconvolute(bulk_mean, method, indications=timer_indications) %>%
                                    map_result_to_celltypes(use_cell_types, method=method) %>%
                                    as_tibble(rownames="cell_type") %>%
                                    mutate(method=method) %>%
                                    mutate(source="mean")
                                }

all_results_simulated_no_mrna_ajust = foreach(method=config$deconvolution_methods,
                                .combine=bind_rows) %do% {
                                  deconvolute(bulk_mean, method, indications=timer_indications, scale_mrna = FALSE) %>%
                                    map_result_to_celltypes(use_cell_types, method=method) %>%
                                    as_tibble(rownames="cell_type") %>%
                                    mutate(method=method) %>%
                                    mutate(source="mean_nomrnaadjust")
                                }
```

```{r}
ref = schelker_ovarian$ref %>% 
  select(sample, cell_type, true_fraction) %>%
  spread(sample, true_fraction) %>%
  map_result_to_celltypes(use_cell_types) %>%
  as.tibble(rownames="cell_type") %>% 
  gather(sample, true_fraction, -cell_type) 

bulk_ref = all_results_bulk %>% 
  gather(sample, estimate, -cell_type, -method, -source) %>%
  inner_join(ref)

simulated_ref = all_results_simulated %>%
  gather(sample, estimate, -cell_type, -method, -source) %>%
  inner_join(ref)

simulated_nomrna_ref = all_results_simulated_no_mrna_ajust %>% 
  gather(sample, estimate, -cell_type, -method, -source) %>%
  inner_join(ref)
```

```{r, fig.width=12, fig.height=7}
bulk_ref %>% 
  ggplot(aes(x=true_fraction, y=estimate)) + geom_point(aes(colour=cell_type)) + 
  facet_wrap(~method, scales = "free") + 
  scale_color_brewer(palette = "Set1") + 
  ggtitle("bulk") + stat_cor()

simulated_ref %>% 
  drop_na() %>%
  ggplot(aes(x=true_fraction, y=estimate)) + geom_point(aes(colour=cell_type)) + 
  facet_wrap(~method, scales = "free") + 
  scale_color_brewer(palette = "Set1") + 
  ggtitle("simulated") + stat_cor()

simulated_nomrna_ref %>% 
  drop_na() %>%
  ggplot(aes(x=true_fraction, y=estimate)) + geom_point(aes(colour=cell_type)) + 
  facet_wrap(~method, scales = "free") + 
  scale_color_brewer(palette = "Set1") + 
  ggtitle("simulated with adjust_mrna=FALSE") + stat_cor()

```
